### PR TITLE
Updated segbot led with new animations and test node

### PR DESCRIPTION
**Pull request by FernandezR**

### CODE REVIEW

**Comment by FernandezR** [comment]
@jack-oquin Would it be possible to do a quick release of bwi_common with the updated LEDAnimations.msg? This pull request won't be able to pass the checks until we do that.

**Comment by jack-oquin** [comment]
Yes, I'll do one soon (and then release segbot and bwi).

The Travis errors are annoying. Maybe we can figure out how to test with unreleased versions of lower-level repositories, but I have not figured out how to do that yet.

**Comment by FernandezR** [comment]
I think it's possible to add git clone to the Travis script, though I'm not sure how to prevent it from also installing the released version.

**Comment by jack-oquin** [comment]
As long as the cloned version is in the same workspace being built, that should work just like it does on our robots.

**Comment by jack-oquin** [comment]
I released bwi_common this morning, so the immediate problem should clear up soon.

**Pull request merged**
